### ISSUE TITLE
When trying to login, there are two password fields

### ISSUE THREAD

**Issue by patdel0** [fac25/week4-karwan-manoela-sumithra-suraj#52]
Upon attempting to login, I am getting the following error:

<details>
<summary>Error</summary>
/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/bcryptjs/dist/bcrypt.js:286
                nextTick(callback.bind(this, Error("Illegal arguments: "+(typeof s)+', '+(typeof hash))));
                                             ^

Error: Illegal arguments: object, string
    at _async (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/bcryptjs/dist/bcrypt.js:286:46)
    at /home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/bcryptjs/dist/bcrypt.js:307:17
    at new Promise (<anonymous>)
    at bcrypt.compare (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/bcryptjs/dist/bcrypt.js:306:20)
    at post (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/src/routes/login.js:39:12)
    at Layer.handle [as handle_request] (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/express/lib/router/layer.js:95:5)
    at /home/zero/Documents/github/week4-karwan-manoela-sumithra-suraj/node_modules/express/lib/router/index.js:284:15

Node.js v18.10.0
[nodemon] app crashed - waiting for file changes before starting...
</details>

**Comment by SurPun** [comment]
Thank you Patrick 🤩, Issue fixed on bb728e2ebac94df9e067d444355b0590007a01cb
